### PR TITLE
Support for docker secrets

### PR DESCRIPTION
**Pull request by 3vilWind**

### CODE REVIEW

**Comment by henriquebastos** [comment]
Sorry. I don't know this format. Can you please explain how it works and why decouple currently do not support it?

**Comment by 3vilWind** [comment]
It is very simple key-value format, where key is a title of the file, value is a content of the file (It is written in the comments to my code).
e.g. When you deploy, Docker mounts a file under /run/secrets/<secret_name> in the services.
/run/secrets/
    - db_user
    - db_password

In my PR there is a simple class which reads files in given directory.

**Comment by melwil** [comment]
Hey, just looked into deployments of django in a docker container, and while I've loved decouple so far, I was missing this. The format is pretty well known by now? Would be great if decouple would support fetching from docker secrets as well!

Here is an example of the format from the docker organization:
https://github.com/docker/build-push-action/blob/master/docs/advanced/secrets.md

**Comment by henriquebastos** [comment]
Had to rebase it and improve tests, but it's in master now. Waiting for a couple pr to release v3.6 maybe next week.

**Comment by melwil** [comment]
Hey, any chance you could make a release with this feature?

**Comment by henriquebastos** [comment]
Just released it.

Em qua., 12 de jan. de 2022 às 07:44, Håvard Slettvold <
***@***.***> escreveu:

**Pull request closed without merging**
